# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian-7-i386"

  config.vm.provision :shell do |sh|
    sh.inline =<<-EOD
    set -x
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    gem install bundler

    wget http://apt.puppetlabs.com/puppetlabs-release-wheezy.deb
    dpkg -i puppetlabs-release-wheezy.deb
    rm puppetlabs-release-wheezy.deb

    apt-get update
    apt-get install -y puppet
    EOD
  end
end
